# version: '3.3'

# volumes:
#   pg_data:
#   static:
#   media:

# services:

#   db:
#     image: postgres:13
#     env_file: .env
#     volumes:
#       - pg_data:/var/lib/postgresql/data

#   backend:
#     image: den4u/CocktailGram_backend
#     env_file: .env
#     volumes:
#       - static:/backend_static
#       - media:/media
#     depends_on:
#       - db

#   frontend:
#     image: den4u/CocktailGram_frontend
#     env_file: .env
#     command: cp -r /app/build/. /frontend_static/
#     volumes:
#       - static:/frontend_static
#     depends_on:
#       - backend

#   nginx:
#     image: den4u/CocktailGram_nginx
#     env_file: .env
#     ports:
#       - 9990:80
#     volumes:
#       - static:/staticfiles
#       - media:/media